// <auto-generated />
namespace Flights.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednametocountries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednametocountries));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081316372_Added name to countries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
