// <auto-generated />
namespace Flights.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changedflightcodedatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedflightcodedatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201801062057539_Changed flight code data type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
